USE [AvaliacaoBD]
GO

CREATE TABLE PRECO (
       COR                  CHAR(2) NOT NULL,
       VALOR                float NOT NULL,
	   CONSTRAINT PK_PRECO PRIMARY KEY (COR)
);


CREATE TABLE CLIENTE (
       CODCLIENTE           int NOT NULL,
       NOME                 CHAR(50) NOT NULL,
       ENDERECO             CHAR(50) NULL,
       BAIRRO               CHAR(20) NULL,
       CIDADE               CHAR(50) NULL,
       ESTADO               CHAR(2) NULL,
	   CONSTRAINT PK_CLIENTE PRIMARY KEY (CODCLIENTE)
);


CREATE TABLE GENERO (
       CODGENERO            int NOT NULL,
       DESCRICAO            CHAR(20) NOT NULL,
	   CONSTRAINT PK_GENERO PRIMARY KEY (CODGENERO)
);


CREATE TABLE FILME (
       CODFILME             int NOT NULL,
       NOME                 CHAR(50) NOT NULL,
       PRECO_COR		    CHAR(2) NOT NULL,
       STATUS               CHAR(1) NOT NULL,
       GENERO_CODGENERO		int NOT NULL,
	   CONSTRAINT PK_FILME PRIMARY KEY (CODFILME)
);


CREATE TABLE LOCACAO (
       CLIENTE_CODCLIENTE   int NOT NULL,
       DATA                 DATE NOT NULL,
       FILME_CODFILME       int NOT NULL,
       DATADEVOLUCAO        DATE NULL,
	   CONSTRAINT PK_LOCACAO PRIMARY KEY (CLIENTE_CODCLIENTE, DATA, FILME_CODFILME)
);


ALTER TABLE FILME ADD CONSTRAINT FK_FILME_GENERO FOREIGN KEY (GENERO_CODGENERO) REFERENCES GENERO (CODGENERO);

ALTER TABLE FILME ADD CONSTRAINT FK_FILME_PRECO FOREIGN KEY (PRECO_COR) REFERENCES PRECO (COR);

ALTER TABLE LOCACAO ADD CONSTRAINT FK_LOCACAO_CLIENTE FOREIGN KEY (CLIENTE_CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE);

ALTER TABLE LOCACAO ADD CONSTRAINT FK_LOCACAO_FILME FOREIGN KEY (FILME_CODFILME) REFERENCES FILME (CODFILME);