USE [AvaliacaoBD]
GO

ALTER TABLE FILME DROP CONSTRAINT FK_FILME_GENERO 

ALTER TABLE FILME DROP CONSTRAINT FK_FILME_PRECO

ALTER TABLE LOCACAO DROP CONSTRAINT FK_LOCACAO_CLIENTE;

ALTER TABLE LOCACAO DROP CONSTRAINT FK_LOCACAO_FILME;

DROP TABLE FILME;

DROP TABLE LOCACAO;

DROP TABLE GENERO;

DROP TABLE CLIENTE;

DROP TABLE PRECO;